(module
  (table 2 anyfunc)
  (func $f1 (param $x i32) (result i32)
    get_local $x )
  (func $f2 (result i32)
    i32.const 20)
  (elem (i32.const 0) $f1 $f2)
  ;; (type $return_i32 (func (param i32) (result i32)))
  ;; (type $return_i32 (anyfunc))
  (func (export "callByIndex") (result i32)
    (i32.const 10)
    (i32.const 0)
    (call_indirect (param i32) (result i32)))
    ;; (call_indirect (type $return_i32)))
)
